package com.example.healthinspector;

public class Constants {
    public static final String PRODUCT_REQUEST_URL = "https://world.openfoodfacts.org/api/v2/product/";
    public static final String SCANNED_PRODUCT = "scannedProduct";
    public static final String PRODUCT = "product";
    public static final String PRODUCT_NAME = "product_name";
    public static final String NUTRISCORE_GRADE = "nutriscore_grade";
    public static final String INGREDIENTS_LIST = "ingredients_text_en";
    public static final String INGREDIENTS_ANALYSIS = "ingredients_analysis_tags";
    public static final String NOVA_GROUP = "nova_group";
    public static final String NUTRIENT_LEVELS = "nutrient_levels";
    public static final String PRODUCT_IMAGE = "image_front_small_url";
    public static final String ALLERGENS = "allergens";
    public static final String ADDITIVES = "additives_tags";
    public static final String ADDITIVES_FILE_NAME = "additives.json";
    public static final String ALLERGENS_FILE_NAME = "allergens.json";
    public static final String FRAGMENT_SWITCH = "fragmentSwitch";
    public static final String PARSE_USER_ALLERGIES = "userAllergies";
    public static final String PARSE_USER_WARNINGS = "userWarningIngredients";
    public static final String SIGN_UP_FLOW = "signUpFlow";
    public static final String CATEGORIES = "categories_tags";
    public static final String PERMISSIONS_GRANTED = "permissions_granted";
    public static final String LOCATION_ID =  "locationId";
    public static final String STORE_NAME =  "storeName";
    public static final String ADDRESS =  "address";
    public static final String LATITUDE =  "latitude";
    public static final String LONGITUDE =  "longitude";
    public static final String DATA =  "data";
    public static final String CART = "cart";
    public static final String KEYWORDS = "keywords";
    public static final String BRAND = "brand";
    public static final String IS_IN_CART = "isInCart";
    public static final String PRODUCT_IMAGE_URL = "product_image_url";
    public static final String IN_STOCK = "in_stock";
    public static final String RECOMMENDED_PRODUCT = "recommended_product";
    public static final int DELAY_SLOW = 2500;
    public static final int DELAY_FAST = 1000;
    public static final int MAX_LOCATIONS = 5;
    public static final int SIGNIFICANT_LOCATION_CHANGE = 2000;
    public static final String URL_REQUEST_PRODUCTS = "https://us.openfoodfacts.org/cgi/search.pl?action=process";
    public static final String PARAM_KEY = "User-Agent";
    public static final String PARAM_VALUE = "Health Inspect - Android - Version 1.0";
    public static final String PRODUCTS = "products";
    public static final String COUNT = "count";
    public static final String AUTHORIZATION = "Authorization";
    public static final int MAP_PADDING = 100;
    public static final String CATEGORY_PARAMS = "&tagtype_%d=categories&tag_contains_%d=contains&tag_%d=%s";
    public static final String LOCATION = "location";
    public static final String NAME = "name";
}
